backend:
  name: git-gateway
  branch: main

# These lines should *not* be indented
media_folder: "public/images" # Media files will be stored in the repo under public/images/
public_folder: "/images" # The src attribute for uploaded media will begin with /images/

collections:
  - name: "blogs" # Used in routes, e.g., /admin/collections/blogs
    label: "Blogs" # Used in the UI
    folder: "cmsContent/blogs" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    format: json
    extension: json
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Intro Blurb", name: "description", widget: "text"}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
